services:
  aiscatcher:
    env_file: 
      - ./.env
      - ./${APPNAME}/${APPNAME}.env
    image: ${REGISTRY}/${MAINTAINER}/${APPNAME}:${TAG}
    build:
      context:  ./${APPNAME}/
      dockerfile: Dockerfile.${APPNAME}
      args:
        - REPOSITORY=jvde-github
        - PROJECT=AIS-catcher
        - BRANCH=main
    container_name: ${CONTAINERNAME}
    hostname:  ${CONTAINERNAME}
    restart: always
    volumes:
      - type: bind
        source: /var/log
        target: /var/log
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    devices:
      - /dev/bus/usb
    tty: true
    networks:
      - ais-containers
    command:
      - "-u"
      - ${FEED_IP}
      - ${FEED_PORT}
      - "-d"
      - "00000001"
      - "-s"
      - "2304K"
      - "-gr"
      - "TUNER"
      - "auto"
      - "RTLAGC"
      - "on"

networks:
  ais-containers:
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: ${IPv4_SUBNET}
        - subnet: ${IPv6_SUBNET}
